CREATE TABLE
    BANK_ACCOUNTS (
        ID INT GENERATED BY DEFAULT AS IDENTITY,
        NAME TEXT NOT NULL,
        BALANCE INT NOT NULL,
        PRIMARY KEY (ID)
    );

INSERT INTO
    bank_accounts (name, balance)
VALUES
    ('Jack', 1000);

-- Commit
BEGIN;

UPDATE bank_accounts
SET
    balance = balance - 100
WHERE
    name = 'Charlie';

UPDATE bank_accounts
SET
    balance = balance + 100
WHERE
    name = 'Dora';

COMMIT;

SELECT
    *
FROM
    bank_accounts;

-- Rollback
BEGIN;

UPDATE bank_accounts
SET
    balance = balance - 1500
WHERE
    name = 'Jack';

SELECT
    *
FROM
    bank_accounts;

UPDATE bank_accounts
SET
    balance = balance + 1500
WHERE
    name = 'Dora';

SELECT
    *
FROM
    bank_accounts;

ROLLBACK;

SELECT
    *
FROM
    bank_accounts;